
=head1 NAME

freindent - Indent and align a XML tags in a FRE XMl file.

=head1 SYNOPSIS

freindent -h

freindent -x I<< <xmlFile> >>

=head1 DESCRIPTION

B<freindent> will insert CDATA tags around your csh for safety.  It
will also substitute in entity values to your xml. If this is not
desired, please try B<xmllint>: C<< xmllint --format in.xml > out.xml >>.




=head1 OPTIONS

=over 8

=item B<-h>

Print the usage message and exit.

=item B<-x> I<< <xmlFile> >>

Use the XML file defined by I<< <xmlFile> >>.

=back

=head1 SEE ALSO

B<xmllint>(1)

=head1 BUGS

=begin man

Report any bugs to GFDL's Helpdesk <oar.gfdl.help@noaa.gov>

=end man

=begin html

<p>Report any bugs to 
<script type="text/javascript">
   <!--
   var contact = "GFDL's Helpdesk";
   var email = "oar.gfdl.help";
   var emailHost = "noaa.gov";
   document.write("<a href=" + "mail" + "to:" + email + "@" + emailHost + ">" + contact + "</a>" + ".");
   //-->
</script>
</p>

=end html

=begin latex

Report any bugs to GFDL's Helpdesk <\texttt{oar.gfdl.help@noaa.gov}>.

=end latex

=begin mediawiki

Report any bugs to GFDL's Helpdesk <oar.gfdl.heml@noaa.gov>

=end mediawiki

=head1 AUTHOR

Designed and written by V. Balaji, Amy Langenhorst and Aleksey Yakovlev

=head1 COPYRIGHT

Copyright 2000-2012 Geophysical Fluid Dynamics Laboratory

The Flexible Modeling System (FMS) is free software; you can
redistribute it and/or modify it and are expected to follow the terms
of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any
later version.

FMS is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
for more details.

=cut
