
=head1 NAME

freppcheck - Checks for missing postprocessing file

=head1 SYNOPSIS

freppcheck [OPTIONS] exp [exp ...]

=head1 DESCRIPTION

B<freppcheck> checks for missing postprocessing files for an arbitary
number of FRE experiments.  By default, B<freppcheck> will only check
one time series variable and not check the time series cpio files.
Before running B<frescrub> for the experiment, it is recommended to
check all files with "freppcheck -A".  After running frescrub, use
"freppcheck -M" to check the cpio files, and not require individual
time series files to be present when a cpio exists.

=head1 OPTIONS

=head2 Component Controlling Options

=over 5

=over 8

=item B<-I>, B<--onlyTA>

Only check the <TimeAverage> nodes.

=item B<-J>, B<--onlyTS>

Only check the <TimeSeries> nodes.

=item B<-G>, B<--Chunks> I<< <STRING> >>

Check the specified subchunks among the chunks specified in the I<<
<xmlfile> >>.  I<< <STRING> >> is a space separated list.

=item B<-F>, B<--Freq> I<< <STRING> >>

Check the specified subfrequency among the frequencies specified in the I<<
<xmlfile> >>.  I<< <STRING> >> is a space separated list.

=item B<-A>, B<--All>

Check all files before frescrub (requires all TS files + cpio files).

=item B<-a>, B<--AllTS>

Check all TS (time series) variables (by default checks only the first TS variable).

=item B<-V>, B<--Variables> I<< <STRING> >>

Check the specified variables only.  I<< <STRING> >> is a space
separated list.

=item B<-M>, B<--requirecpio>

Requires cpio files, does not require individual files.

=item B<-L>, B<--filesize>

Print the file size, which can provide a clue to the correct number
of time steps in the TS variable files.

=item B<-c>, B<--component> I<< <STRING> >>

Check only the specified component.

=item B<-d>, B<--dir> I<< <PATH> >>

Path to override the default history directory. The history directory is only
used to get the range of years of history data available for postprocessing.

=item B<-D>, B<--ppdir> I<< <PATH> >>

Path to override the default postprocessing directory. This can be used
to check someone else's postprocessing files, or can be used when the
postprocessing files are in a nonstandard location.

=item B<-b>, B<--beginyear> I<< <STRING> >>

First year to check.  If omitted, B<freppcheck> will prompt you for
it.

=item B<-e>, B<--endyear> I<< <STRING> >>

Last year to check.  If omitted, B<freppcheck> will prompt you for it.

=item B<-g>, B<--generate>

Generate state files containing "OK" for the years being checked.

=back

=back

=head2 General FRE Options

=over 5

=over 8

=item B<-x>, B<--xmlfile> I<< <xmlFile> >>

Use the XML file defined by I<< <xmlFile> >>.  Default: F<$cwd/rts.xml>.

=item B<-v>, B<--verbose>

Verbose messages.  Option can be repeated to increase the verbosity.

=item B<-h>, B<--help>

Print the usage message and exit.

=item B<-p>, B<--platform> I<< <PLATFORM> >>

Use this platform from the XML to setup the specific hardware and
software the experiment will be built and run on.  For postprocessing
runs made at remote sites, I<< <PLATFORM> >> is
of the form <site>.<run-site>-<software>.  Default: gfdl.ncrc2-default.

=item B<-t>, B<--target> I<< <STRING> >>

The compilation target. For postprocessing, the target should be the same
as was used for the model run.

=item I<exp>

At least one experiment from the I<< <xmlFile> >> must be listed as an
argument.  Run B<frelist> to get a list of available experiments.

=back

=back

=head1 SEE ALSO

B<frelist>(1), B<frescrub>(1)

=head1 BUGS

=begin man

Report any bugs to GFDL's Helpdesk <oar.gfdl.help@noaa.gov>

=end man

=begin html

<p>Report any bugs to 
<script type="text/javascript">
   <!--
   var contact = "GFDL's Helpdesk";
   var email = "oar.gfdl.help";
   var emailHost = "noaa.gov";
   document.write("<a href=" + "mail" + "to:" + email + "@" + emailHost + ">" + contact + "</a>" + ".");
   //-->
</script>
</p>

=end html

=begin latex

Report any bugs to GFDL's Helpdesk <\texttt{oar.gfdl.help@noaa.gov}>.

=end latex

=begin mediawiki

Report any bugs to GFDL's Helpdesk <oar.gfdl.heml@noaa.gov>

=end mediawiki

=head1 AUTHOR

Designed and written by V. Balaji, Amy Langenhorst and Aleksey Yakovlev

=head1 COPYRIGHT

Copyright 2000-2012 Geophysical Fluid Dynamics Laboratory

The Flexible Modeling System (FMS) is free software; you can
redistribute it and/or modify it and are expected to follow the terms
of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any
later version.

FMS is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
for more details.

=cut
