
=head1 NAME

frepp - FRE postprocessing utility




=head1 SYNOPSIS

frepp [OPTIONS] exp [exp ...]




=head1 DESCRIPTION

B<frepp> is the FRE postprocessing utility.




=head1 OPTIONS

=head2 Options for Combining Multiprocessor History Files

=over 5

=over 8

=item B<-f>, B<--forceCombine>

Force combine of all raw history files that exist for the experiment, then exit.

=back

=back



=head2 Options for Refining History Files Before Postprocessing

=over 5

=over 8

=item B<-D>, B<--refineDiag> I<< <script> >>

I<< <scripts> >> is a comma separated list of scripts that B<frepp> will use to run on history data.

=item B<-H>, B<--refineDiagOnly>

Do refineDiag only: do not do regular frepp processing.

=back

=back


=head2 Options for Postprocessing Data

=over 5

=over 8

=item B<-t>, B<--time> I<< <time> >>

Beginning of model year to process.  To process 1982, use '-t 1982' or
'-t 10820101'.

=item B<-c>, B<--component> I<< <component> >>

The component to be processed, or perform parallel postprocessing over
all components with the keyword 'split'. By default, perform parallel
postprocessing over all components.

=item B<-m> I<< <STRING> >>

Options to pass to the scheduler.

=item B<-d>, B<--dir>, B<--history> I<< <dir> >>

Path to history data to be postprocessed.

=item B<-o>, B<--override>

Override job dependencies.

=item B<-u>, B<--unique> I<< <STRING> >>

Write postprocessing output to a new unique directory.  The I<< <STRING>
>> value will be appended to the postprocessing output directory,
e.g. if 'frepp -u 2' will produce F<.../pp_2>.

=item B<-l>, B<--limitstatic>

Limit static variables processing to the diag source file in the XML.

=item B<-p>, B<--plus> I<< <num> >>

Additional years to process after the first year. DEPRECATED.

=item B<-w>, B<--wait> I<< <jobid> >>

Place a hold on the current job so that is waits for I<< jobid> >> to
complete.

=back

=back



=head2 Options for Analysis Figures

=over 5

=over 8

=item B<-A>, B<--AnalysisOnly>

Run the analysis only.

=item B<-R>, B<--Regenerate>

Regenerate, submit analysis scrips regardless of wheter they already exist.

=item B<-O>, B<--OutputFigureDir> I<< <directory> >>

Directory where the output figures should go.  This argument is
normally used with the B<-A> (run analysis only) option.  This option
is required if the XML file is not owned by the user running B<frepp>.

=item B<-Y>, B<--AnalysisStartYear> I<< <year> >>

Specify a four didgit year as your analysis' start year, e.g. '-Y
1994'.  This year overrides the I<startYear> in the XML file's
<analysis> tag.

=item B<-Z>, B<--AnalysisEndYear> I<< <year> >>

Specify a four digit year as your analysis' end year, e.g. '-Z 1985'.
This year overrides the I<endYear> specified in the XML file's
<analysis> tag.

=back

=back



=head2 Options for Timing / Debugging / Statistics

=over 5

=over 8

=item B<-M>, B<--MailOnComplete>

Send mail to the user when job is complete.

=item B<-W>, B<--Walltime> I<< <time> >>

Change the max wallclock time for the job.  The time format should be
HH:MM:SS.  Default: 60:00:00.

=item B<-Q>, B<--debug>

Don't print the error checks into the script.  For evaluating csh.

=item B<-q>, B<--quiet>

don't print the analysis figure checks to stdout.

=item B<-v>, B<--verbose>

Be verbose in the output.

=item B<-V>, B<--VeryVerbose>

Be extremely verbose in the output.

=back

=back



=head2 General FRE Options

=over 5

=over 8

=item B<-h>, B<--help>

Print the useage message and exit.

=item B<-r>, B<--runparams> I<< <runparams> >>

Regression test run.  Combine I<netCDF> files, but no further processing.

=item B<-s>, B<--submit>

Automatically submit the script to the queuing system.

=item B<-x>, B<--xmlfile> I<< <xmlfile> >>

Specify the XML file.  Default: I<$cwd/rts.xml>.

=item B<-P>, B<--platform> I<< <PLATFORM> >>

Use this platform from the XML to setup the specific hardware and
software the experiment will be built and run on.  For postprocessing
runs made at remote sites, I<< <PLATFORM> >> is
of the form <site>.<run-site>-<software>.  Default: gfdl.ncrc2-default.

=item B<-T>, B<--target> I<< <STRING> >>

The compilation target. For postprocessing, the target should be the same
as was used for the model run.

=item I<exp>

At least one experiment from the I<< <xmlFile> >> must be listed as an argument.  Run B<frelist> to get a list of available experiments.

=back

=back



=head1 SEE ALSO

B<mppnccombine>, B<frelist>




=head1 BUGS

=begin man

Report any bugs to GFDL's Helpdesk <oar.gfdl.help@noaa.gov>

=end man

=begin html

<p>Report any bugs to
<script type="text/javascript">
   <!--
   var contact = "GFDL's Helpdesk";
   var email = "oar.gfdl.help";
   var emailHost = "noaa.gov";
   document.write("<a href=" + "mail" + "to:" + email + "@" + emailHost + ">" + contact + "</a>" + ".");
   //-->
</script>
</p>

=end html

=begin latex

Report any bugs to GFDL's Helpdesk <\texttt{oar.gfdl.help@noaa.gov}>.

=end latex

=begin mediawiki

Report any bugs to GFDL's Helpdesk <oar.gfdl.heml@noaa.gov>

=end mediawiki




=head1 AUTHOR

=begin man

Amy Langenhorst <Amy.Langenhorst@noaa.gov>

=end man

=begin html

<p>
<script type="text/javascript">
   <!--
   var contact = "Amy Langenhorst";
   var email = "Amy.Langenhorst";
   var emailHost = "noaa.gov";
   document.write("<a href=" + "mail" + "to:" + email + "@" + emailHost + ">" + contact + "</a>" + ".");
   //-->
</script>
</p>

=end html

=begin latex

Amy Langenhorst <\texttt{Amy.Langenhorst@noaa.gov}>

=end latex




=head1 COPYRIGHT

Copyright 2000-2012 Geophysical Fluid Dynamics Laboratory

The Flexible Modeling System (FMS) is free software; you can
redistribute it and/or modify it and are expected to follow the terms
of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any
later version.

FMS is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
for more details.

=cut
