before_script:
  - hostname

ncrc3:
  tags:
    - ncrc3
  variables:
    FRE_COMMANDS_TEST: ${CI_PROJECT_DIR}
  script:
    - source /usr/local/Modules/default/init/bash
    - module unuse /ncrc/home2/fms/local/modulefiles
    - module use /ncrc/home2/fms/local/modulefiles_test
    - module load fre/test
    - export PATH="${PATH}:/lustre/f1/unswept/Carlo.Rosati/opt/local/libexec"
    - ./t/FRE_tests/run_tests

ncrc4:
  tags:
    - ncrc4
  variables:
    FRE_COMMANDS_TEST: ${CI_PROJECT_DIR}
  script:
    - source /usr/local/Modules/default/init/bash
    - module unuse /ncrc/home2/fms/local/modulefiles
    - module use /ncrc/home2/fms/local/modulefiles_test
    - module load fre/test
    - export PATH="${PATH}:/lustre/f1/unswept/Carlo.Rosati/opt/local/libexec"
    - ./t/FRE_tests/run_tests
