before_script:
  - hostname

ncrc3:
  tags:
    - ncrc3
  variables:
    FRE_COMMANDS_TEST: ${CI_PROJECT_DIR}
  script:
    - source /opt/modules/default/init/bash
    - module unuse /ncrc/home2/fms/local/modulefiles
    - module use /ncrc/home2/fms/local/modulefiles_test
    - module load fre/test
    - cd t/FRE_tests
    - ./run_tests

ncrc4:
  tags:
    - ncrc4
  variables:
    FRE_COMMANDS_TEST: ${CI_PROJECT_DIR}
  script:
    - source /opt/cray/pe/modules/default/init/bash
    - module unuse /ncrc/home2/fms/local/modulefiles
    - module use /ncrc/home2/fms/local/modulefiles_test
    - module load fre/test
    - cd t/FRE_tests
    - ./run_tests

theia:
  tags:
    - theia
  variables:
    FRE_COMMANDS_TEST: ${CI_PROJECT_DIR}
  script:
    - source /apps/lmod/lmod/init/bash
    - module unuse /home/fms/local/modulefiles
    - module use /home/fms/local/modulefiles_test
    - module load fre/test
    - cd t/FRE_tests
    - ./run_tests

gfdl-ws:
  tags:
    - gfdl-ws
  variables:
    FRE_COMMANDS_TEST: ${CI_PROJECT_DIR}
  script:
    - source /usr/local/Modules/default/init/bash
    - module unuse /home/fms/local/modulefiles
    - module use /home/fms/local/modulefiles_test
    - module load fre/test
    - cd t/FRE_tests
    - ./run_tests

gfdl:
  tags:
    - gfdl
  variables:
    FRE_COMMANDS_TEST: ${CI_PROJECT_DIR}
  script:
    - source /usr/share/Modules/init/bash
    - module unuse /home/fms/local/modulefiles
    - module use /home/fms/local/modulefiles_test
    - module load fre/test
    - cd t/FRE_tests
    - ./run_tests
