before_script:
  - hostname

.testScript: &testScript
  script:
    - source ${MODULESHOME}/init/bash
    - module use ${FMS_HOME}/local/modulefiles
    - if [ "X$(module avail slurm 2>&1)" != "X" ]; then module load slurm; fi
    - module load fre/test
    - if [[ -n $(module avail bats 2>&1) ]]; then module load bats; fi
    - module list
    - cd t/FRE_tests
    - ./run_tests

.deployScript: &deployScript
  only:
    - master
  script:
    - ${CI_PROJECT_DIR}/t/FRE_tests/run_tests

ncrc5:
  tags:
    - ncrc5
  variables:
    FRE_COMMANDS_TEST: ${CI_PROJECT_DIR}
    FMS_HOME: /ncrc/home2/fms
  script:
    - source ${MODULESHOME}/init/bash
    - module use ${FMS_HOME}/local/modulefiles
    - module load fre/test
    - module list
    - PATH=/ncrc/home2/Oar.Gfdl.Fre_test/opt/bats/1.11.0/bin:${PATH} && export PATH
    - cd t/FRE_tests
    - ./run_tests

gfdl-ws:
  tags:
    - gfdl-ws
  variables:
    FRE_COMMANDS_TEST: ${CI_PROJECT_DIR}
    MODULESHOME: /usr/local/Modules/default
    FMS_HOME: /home/fms
  allow_failure: true
  <<: *testScript

gfdl:
  tags:
    - gfdl
  variables:
    FRE_COMMANDS_TEST: ${CI_PROJECT_DIR}
    MODULESHOME: /usr/local/Modules/default
    FMS_HOME: /home/fms
  <<: *testScript

stage:ncrc:
   stage: deploy
   environment:
     name: stage_ncrc
   tags:
      - ncrc_deploy
   variables:
      FRE_COMMANDS_DIR: /ncrc/home2/fms/local/opt/fre-commands/test
   <<: *deployScript

.stage:theia:
   stage: deploy
   environment:
     name: stage_theia
   tags:
      - theia_deploy
   variables:
      FRE_COMMANDS_DIR: /home/fms/local/opt/fre-commands/test
   <<: *deployScript

stage:gfdl:
   stage: deploy
   environment:
     name: stage_gfdl
   tags:
      - gfdl-ws_deploy
   variables:
      FRE_COMMANDS_DIR: /home/fms/local/opt/fre-commands/test
   <<: *deployScript
