#!/bin/bash

case $FRE_SYSTEM_SITE in
	gfdl )
		PATH=$PATH:/home/sdu/opt/bats/bin
		;;
	ncrc2 )
		PATH=$PATH:/ncrc/home2/Seth.Underwood/opt/bats/0.4.0/bin
		;;
esac

cd xml

command="bats -t ../frelist.bats"
echo $command
$command

echo ""
command="bats -t ../fremake.bats"
echo $command
$command

echo ""
command="bats -t ../frerun.bats"
echo $command
$command

cd ..
