'\" t
.\"     Title: ardiff
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/09/2014
.\"    Manual: FRE Utility
.\"    Source: FRE Bronx-9
.\"  Language: English
.\"
.TH "ARDIFF" "1" "12/09/2014" "FRE Bronx\-9" "FRE Utility"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ardiff \- utility for diffing cpio or tar archives containing netcdf files and text files
.SH "SYNOPSIS"
.sp
.nf
ls \-1 <ARCHIVE_FILES> | ardiff [OPTIONS]
ardiff < <ARCHIVE_FILE_LIST>
.fi
.SH "DESCRIPTION"
.sp
\fBardiff\fR takes a list of *\&.cpio or *\&.tar files as input\&. It extracts the archive into a temporary folder and compares the files in the first archive to the corresponding files in the second archive\&. It then compares the first archive to the third, etc\&.
.sp
\fBardiff\fR compares first with \fBcmp\fR\&. If that fails it uses the \fBnccmp\fR utility written by Remik Ziemlinski\&.
.sp
By default, \fBardiff\fR calls \fBnccmp\fR with the options \fI\-mdq\fR (compare metadata, data, and quiet)\&.
.SH "OPTIONS"
.SS "ARDIFF Specific Options"
.PP
\fB\-s\fR
.RS 4
Save the temporary directory containing the restart files extracted for the archives\&.
.RE
.PP
\fB\-c\fR \fI<COPY_TOOL>\fR
.RS 4
Set the tool used to copy files\&. Default:
\fBgcp\fR\&.
.RE
.PP
\fB\-q\fR
.RS 4
Quiet run\&. Do not print
\fBcpio\fR/\fBtar\fR
warnings\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print the usage message and exit\&.
.RE
.PP
\fI<ARCHIVE_FILES>\fR
.RS 4
A space separated list of *\&.cpio or *\&.tar files to compare\&.
.RE
.PP
\fI<ARCHIVE_FILE_LIST>\fR
.RS 4
A file containing a list of *\&.cpio or *\&.tar files to compare\&.
.RE
.SS "NCCMP Controlling Options"
.PP
\fB\-f\fR
.RS 4
Forcefully compare archives, do not stop after the first difference\&.
.RE
.PP
\fB\-g\fR
.RS 4
Compare global NetCDF attributes\&.
.RE
.PP
\fB\-v\fR \fIvar1[,\&...]\fR
.RS 4
Compare variable(s)
\fIvar1[,\&...]\fR
only\&.
.RE
.PP
\fB\-x\fR \fIvar1[,\&...]\fR
.RS 4
Exclude variable(s)
\fIvar1[,\&...]\fR\&.
.RE
.PP
\fB\-A\fR \fIatt1[,\&...]\fR
.RS 4
Ignore attribute(2)
\fIatt1[,\&...]\fR\&. for all variables\&.
.RE
.PP
\fB\-I\fR \fI<FILE>\fR
.RS 4
Ignore differences for file\&. (Repeatable)
.RE
.SH "SEE ALSO"
.sp
\fBtar\fR(1), \fBcpio\fR(1), \fBnccmp \-h\fR, \fBcmp\fR(1), \fBgcp\fR(1)
.SH "BUGS"
.sp
Send bug reports to GFDL\(cqs Helpdesk <oar\&.gfdl\&.help@noaa\&.gov>\&.
.SH "AUTHORS"
.sp
Designed and written by Amy Langenhorst\&.
.SH "COPYRIGHT AND LICENSE"
.sp
Copyright 2000\-2012 Geophysical Fluid Dynamics Laboratory
.sp
The Flexible Modeling System (FMS) is free software; you can redistribute it and/or modify it and are expected to follow the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.sp
FMS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
