'\" t
.\"     Title: frerts_check
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/09/2014
.\"    Manual: FRE Utility
.\"    Source: FRE Bronx-9
.\"  Language: English
.\"
.TH "FRERTS_CHECK" "1" "12/09/2014" "FRE Bronx\-9" "FRE Utility"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
frerts_check \- Checks status of frerts output data
.SH "SYNOPSIS"
.sp
.nf
frerts_check [OPTIONS] exp [exp \&...]
.fi
.SH "DESCRIPTION"
.sp
\fBfrerts_check\fR checks and compares the frerts output data
.SH "OPTIONS"
.PP
\fB\-\-force\fR
.RS 4
Do not stop comparing netcdf files after the first difference\&.
.RE
.PP
\fB\-\-Longlist\fR
.RS 4
List all the restart files in the long format, do not compare them\&.
.RE
.PP
\fB\-\-list\fR
.RS 4
List all the restart files in the short format, do not compare them\&.
.RE
.PP
\fB\-\-platform\fR \fI<PLATFORM>\fR
.RS 4
Hardware and software platform
\fI<PLATFORM>\fR\&.
.RE
.sp
\fB\-\-Attribute\fR \fI<ATTRIBUTE>\fR Ignore the attribute(s) att1[,\&...] for all fields\&.
.PP
\fB\-\-Save\fR
.RS 4
Save all the temporary files, created by the ardiff command\&.
.RE
.PP
\fB\-\-start\-date\fR \fI<DATE>\fR
.RS 4
Start date to override the date from the configuration file\&.
.RE
.PP
\fB\-\-target\fR \fI<TARGET>\fR
.RS 4
Use compilation directives, targeted by
\fI<TARGET>\fR\&.
.RE
.PP
\fB\-\-timing\fR
.RS 4
Print timings only, do not compare restart files\&.
.RE
.PP
\fB\-\-xmlfile\fR \fI<XMLFILE>\fR
.RS 4
Experiment suite configuration
\fI<XMLFILE>\fR\&.
.RE
.PP
\fB\-\-ignore_var_list\fR \fI<VARLIST>\fR
.RS 4
List of variables being ignored in comparisons\&.
.RE
.PP
\fB\-\-ignore_file_list\fR \fI<FILELIST>\fR
.RS 4
List of file/directory names/pattern being ignored in comparisons\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print help message and exit\&.
.RE
.PP
\fB\-\-Version\fR
.RS 4
Print the tool version and exit\&.
.RE
.PP
\fB\-\-verbose\fR
.RS 4
Get verbose messages (repeat the option to increase verbosity level)\&.
.RE
.SH "BUGS"
.sp
Send bug reports to GFDL\(cqs Helpdesk <oar\&.gfdl\&.help@noaa\&.gov>\&.
.SH "AUTHORS"
.sp
Designed and written by Niki Zadeh\&.
.SH "COPYRIGHT AND LICENSE"
.sp
Copyright 2011\-2012 Geophysical Fluid Dynamics Laboratory
.sp
The Flexible Modeling System (FMS) is free software; you can redistribute it and/or modify it and are expected to follow the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.sp
FMS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
