'\" t
.\"     Title: frerts.csh
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/09/2014
.\"    Manual: FRE Utility
.\"    Source: FRE Bronx-9
.\"  Language: English
.\"
.TH "FRERTS\&.CSH" "1" "12/09/2014" "FRE Bronx\-9" "FRE Utility"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
frerts.csh \- Creates and runs frerts scripts\&.
.SH "SYNOPSIS"
.sp
.nf
frerts\&.csh [OPTIONS] exp [exp \&...]
.fi
.SH "DESCRIPTION"
.sp
\fBfrerts\&.csh\fR will create and run frerts scripts for a given FRE XML, with a given platform, target, and list of experiments\&.
.sp
To run a suite of XMLs, platforms, targes, and experiments see \fBfrerts_batch\&.csh\fR(1)\&.
.SH "OPTIONS"
.PP
\fB\-x\fR \fI<xmlFile>\fR
.RS 4
Use the XML file defined by <xmlFile>\&.
.RE
.PP
\fB\-p\fR \fI<PLATFORM>\fR
.RS 4
Use this platform from the XML to setup the specific hardware and software the experiment will be built and run on\&.
\fI<PLATFORM>\fR
is of the form <site>\&.<software>\&. <site> must be one of the following (ncrc1, ncrc2, gfdl, \&...), and <software> can be any descriptive string (no spaces), or "default"\&. <site> is dependent on where B<fremake> is executed\&. Default: <site>\&.default\&.
.RE
.PP
\fB\-t\fR \fI<TARGET>\fR
.RS 4
The compilation target\&. Predefined targets strings are
\fIrepro\fR,
\fIprod\fR,
\fIdebug\fR,
\fIhdf5\fR
and
\fIopenmp\fR\&. The targets can be combined using a comma separated list (e\&.g\&. prod,openmp)\&. Default:
\fIprod\fR\&.
.RE
.sp
The targets \fIprod\fR, \fIrepro\fR and \fIdebug\fR are mutually exclusive\&. Not more than one of these is allowed in the target list\&.
.sp
User defined targets should refer to a <compile> node with the corresponding value of its target attribute\&.
.PP
\fB\-\-compile\fR
.RS 4
Optionally compile if passed\&.
.RE
.PP
\fB\-l\fR \fI<LIB_EXPERIMENT_NAME>\fR
.RS 4
The experiment that contains required libraries\&.
.RE
.PP
\fB\-\-build_only\fR
.RS 4
Optionally do only the compilation and exit\&.
.RE
.PP
\fB\-\-all\fR
.RS 4
Optionally run all the experiments in the xml that do not contain "noRTS" in their name\&.
.RE
.PP
\fB\-\-no_rts\fR
.RS 4
Optionally run only the "basic" regression and do not run the "rts" regression\&.
.RE
.PP
\fB\-\-no_stage\fR
.RS 4
Optionally do not stage the data and use "frerun \-s" (assumes the data is pre\-staged to ptmp)
.RE
.PP
\fB\-\-fre_version\fR _<FRE_VERSION>
.RS 4
Specify the FRE version\&.
.RE
.PP
\fB\-\-fre_ops\fR \fI<FRERUN_OPTS>\fR
.RS 4
Optionally passes a list of options to
\fBfrerun\fR\&. The
\fI<FRERUN_OPTS>\fR
is a semicolon separated list of
\fBfrerun\fR
options (see
\fBfrerun\fR(1) for available options)\&.
.RE
.PP
\fB\-\-dry_run\fR
.RS 4
Do not submit any jobs, just print the
\fBfrerun\fR
commands
\fBfrerts\&.csh\fR
will execute\&.
.RE
.PP
\fIexp\fR
.RS 4
Experiment from the
\fI<xmlFile>\fR\&. Run
\fBfrelist\fR
to get a list of available experiments\&.
.RE
.SH "SEE ALSO"
.sp
\fBfrelist\fR(1), \fBfrerun\fR(1), \fBfrerts_batch\&.csh\fR(1)
.SH "BUGS"
.sp
Send bug reports to GFDL\(cqs Helpdesk <oar\&.gfdl\&.help@noaa\&.gov>\&.
.SH "AUTHORS"
.sp
Designed and written by Niki Zadeh\&.
.SH "COPYRIGHT AND LICENSE"
.sp
Copyright 2011\-2012 Geophysical Fluid Dynamics Laboratory
.sp
The Flexible Modeling System (FMS) is free software; you can redistribute it and/or modify it and are expected to follow the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.sp
FMS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
