'\" t
.\"     Title: frerts_batch.csh
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/09/2014
.\"    Manual: FRE Utility
.\"    Source: FRE Bronx-9
.\"  Language: English
.\"
.TH "FRERTS_BATCH\&.CSH" "1" "12/09/2014" "FRE Bronx\-9" "FRE Utility"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
frerts_batch.csh \- Creates and runs frerts scripts\&.
.SH "SYNOPSIS"
.sp
.nf
frerts_batch\&.csh [OPTIONS] exp [exp \&...]
.fi
.SH "DESCRIPTION"
.sp
\fBfrerts_batch\&.csh\fR will create and run a suite of frerts scripts for a list of FRE XML\(cqs with a list of platforms, targets and list of experiments\&.
.SH "OPTIONS"
.PP
\fB\-d\fR \fI<XML_DIRECTORY>\fR
.RS 4
Directory that contains the XMLs\&. Defaults:
\fI$cwd\fR\&.
.RE
.PP
\fB\-x\fR \fI<xmlFile_LIST>\fR
.RS 4
Comma separated list of XML files to use\&.
.RE
.PP
\fB\-p\fR \fI<PLATFORM_LIST>\fR
.RS 4
Comma separated list of platforms\&. See description of
\fI\-p\fR
in
\fBfrerts\&.csh\fR(1)\&.
.RE
.PP
\fB\-t\fR \fI<TARGET_LIST>\fR
.RS 4
Comma separated list of targets\&. See description of
\fI\-t\fR
in
\fBfrerts\&.csh\fR(1)\&.
.RE
.PP
*\-\-frerts_ops \fI<FRERTS_OPTIONS>\fR
.RS 4
Comma separated list of
\fBfrerts\&.csh\fR
options\&. See
\fBfrerts\&.csh\fR(1) for available options\&.
.RE
.PP
\fIexp\fR
.RS 4
Experiment from the
\fI<xmlFile>\fR\&. Run
\fBfrelist\fR
to get a list of available experiments\&.
.RE
.SH "SEE ALSO"
.sp
\fBfrelist\fR(1), \fBfrerts\&.csh\fR(1)
.SH "BUGS"
.sp
Send bug reports to GFDL\(cqs Helpdesk <oar\&.gfdl\&.help@noaa\&.gov>\&.
.SH "AUTHORS"
.sp
Designed and written by Niki Zadeh\&.
.SH "COPYRIGHT AND LICENSE"
.sp
Copyright 2011\-2012 Geophysical Fluid Dynamics Laboratory
.sp
The Flexible Modeling System (FMS) is free software; you can redistribute it and/or modify it and are expected to follow the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.sp
FMS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
