'\" t
.\"     Title: list_paths
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/09/2014
.\"    Manual: FRE Utility
.\"    Source: FRE Bronx-9
.\"  Language: English
.\"
.TH "LIST_PATHS" "1" "12/09/2014" "FRE Bronx\-9" "FRE Utility"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
list_paths \- Scan a directory tree for source files
.SH "SYNOPSIS"
.sp
.nf
list_paths [OPTIONS] <dir> [<dir> \&...]
.fi
.SH "DESCRIPTION"
.sp
\fBlist_paths\fR will scan a directory tree for source files (files with names of *\&.{c,C,f,F,fh,f90,F90,h,H,inc}) and documentation files (files with names of *\&.{html,ps,txt}, README and readme)\&. The source list output file can be passed to the Makefile creation utility \fBmkmf\fR to assist in creating a Makefile to be used with \fBmake\fR\&.
.SH "OPTIONS"
.PP
\fB\-o\fR \fI<OUTPUT_FILE>\fR
.RS 4

\fI<OUTPUT_FILE>\fR
will have a list of all source files (files with a name of *\&.{c,C,f,F,fh,f90,F90,h,H,inc})\&. and
\fI<OUTPUT_FILE>\&.html\fR
will have a list of documentation fils (files with a name of \e*\&.{html,ps,txt}, README or readme)
.RE
.SH "SEE ALSO"
.sp
\fBmkmf\fR(1), \fBmake\fR(1)
.SH "BUGS"
.sp
Send bug reports to GFDL\(cqs Helpdesk <oar\&.gfdl\&.help@noaa\&.gov>\&.
.SH "AUTHORS"
.sp
Designed and written by V\&. Balaji\&.
.SH "COPYRIGHT AND LICENSE"
.sp
Copyright 2000\-2007 Geophysical Fluid Dynamics Laboratory
.sp
The Flexible Modeling System (FMS) is free software; you can redistribute it and/or modify it and are expected to follow the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.sp
FMS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
