'\" t
.\"     Title: list_files_with_tag
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/09/2014
.\"    Manual: FRE Utility
.\"    Source: FRE Bronx-9
.\"  Language: English
.\"
.TH "LIST_FILES_WITH_TAG" "1" "12/09/2014" "FRE Bronx\-9" "FRE Utility"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
list_files_with_tag \- Return a list of files in CVS with a given tag name
.SH "SYNOPSIS"
.sp
.nf
list_files_with_tag <cvs_tag>
.fi
.SH "DESCRIPTION"
.sp
\fBlist_files_with_tag\fR will return a list of files under CVS control, relative to the current directory, which can be updated or checked out with the \fI<cvs_tag>\fR tag or branch name\&.
.SH "OPTIONS"
.PP
\fI<cvs_tag>\fR
.RS 4
A CVS tag or branch name\&.
.RE
.SH "SEE ALSO"
.sp
\fBcvs\fR(1)
.SH "BUGS"
.sp
Send bug reports to GFDL\(cqs Helpdesk <oar\&.gfdl\&.help@noaa\&.gov>\&.
.SH "AUTHORS"
.sp
Designed and written by V\&. Balaji, Amy Langenhorst and Aleksey Yakovlev\&.
.SH "COPYRIGHT AND LICENSE"
.sp
Copyright 2000\-2012 Geophysical Fluid Dynamics Laboratory
.sp
The Flexible Modeling System (FMS) is free software; you can redistribute it and/or modify it and are expected to follow the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.sp
FMS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
