.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "VERSIONS" "1" "08/01/2012" "FRE Bronx" "FRE Utility"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
versions \- A terse cvs status wrapper
.SH "SYNOPSIS"
.sp
.nf
versions [<args>]
.fi
.SH "DESCRIPTION"
\fBversions\fR is a wrapper to 'cvs status' that is more terse in its output. Mainly prints only filename, and CVS branch/version number, and the current status of the file.
.sp
.SH "OPTIONS"
.TP
\fI<args>\fR
Additional options/directories to pass to
\fIcvs status\fR.
.SH "SEE ALSO"
\fBcvs\fR(1)
.sp
.SH "BUGS"
Send bug reports to GFDL's Helpdesk <oar.gfdl.help@noaa.gov>.
.sp
.SH "AUTHORS"
Designed and written by V. Balaji, Amy Langenhorst and Aleksey Yakovlev.
.sp
.SH "COPYRIGHT AND LICENSE"
Copyright 2000\-2012 Geophysical Fluid Dynamics Laboratory
.sp
The Flexible Modeling System (FMS) is free software; you can redistribute it and/or modify it and are expected to follow the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.sp
FMS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.sp
