'\" t
.\"     Title: versions
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/09/2014
.\"    Manual: FRE Utility
.\"    Source: FRE Bronx-9
.\"  Language: English
.\"
.TH "VERSIONS" "1" "12/09/2014" "FRE Bronx\-9" "FRE Utility"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
versions \- A terse cvs status wrapper
.SH "SYNOPSIS"
.sp
.nf
versions [<args>]
.fi
.SH "DESCRIPTION"
.sp
\fBversions\fR is a wrapper to \'cvs status\e\' that is more terse in its output\&. Mainly prints only filename, and CVS branch/version number, and the current status of the file\&.
.SH "OPTIONS"
.PP
\fI<args>\fR
.RS 4
Additional options/directories to pass to
\fIcvs status\fR\&.
.RE
.SH "SEE ALSO"
.sp
\fBcvs\fR(1)
.SH "BUGS"
.sp
Send bug reports to GFDL\(cqs Helpdesk <oar\&.gfdl\&.help@noaa\&.gov>\&.
.SH "AUTHORS"
.sp
Designed and written by V\&. Balaji, Amy Langenhorst and Aleksey Yakovlev\&.
.SH "COPYRIGHT AND LICENSE"
.sp
Copyright 2000\-2012 Geophysical Fluid Dynamics Laboratory
.sp
The Flexible Modeling System (FMS) is free software; you can redistribute it and/or modify it and are expected to follow the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.sp
FMS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
